# Generated by Django 3.2.5 on 2021-07-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_alter_contato_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=255),
        ),
    ]
