# Generated by Django 3.2.5 on 2021-07-28 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_auto_20210728_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='data_criação',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
